AWSTemplateFormatVersion: '2010-09-09'
Description: Launch EC2 instance from shared AMI

Parameters:
  InstanceType:
    Type: String  # EC2 instance type
    Default: t2.micro
  SharedAmiId:
    Type: String  # The ID of the shared AMI
    Default: ami-08d65f2070be0f0ef
  VPCId:
    Type: AWS::EC2::VPC::Id  # The VPC in which to launch the instance
  SubnetId:
    Type: AWS::EC2::Subnet::Id  # The subnet in which to launch the instance
  Env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Conditions: 
  CreateProdResources: !Equals [ !Ref Env, prd ]

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref SharedAmiId
      SubnetId: !Ref SubnetId  # Set the subnet for the instance
      KeyName: !Sub "database-connection-ec2-${Env}"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "rds-database-connection-${Env}"

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref EC2Instance
  InstanceSecurityGroupId:
    Description: Security Group ID of the created EC2 instance
    Value: !Ref InstanceSecurityGroup