apiVersion: v1
kind: Service
metadata:
  name: mockserver-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: mockserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
