apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mydatabase
  name: mydatabase
spec:
  containers:
  - image: mysql:5.7
    name: mydatabase
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
