kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume  
  labels:
    type: local
    app: postgres-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: gp2  # AWS General Purpose SSD
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi