AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  PublicSubnetA:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for the ECS task placement
  PublicSubnetB:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for the ECS task placement
  PublicSubnetC:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for the ECS task placement
  DefaultVPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the ECS task placement
  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group for the ECS task
  Env:
    Type: String
    AllowedValues:
      - dev

Resources:
  # Application Load Balancer Configuration
  AtlantisServerLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
        - !Ref PublicSubnetC
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref LBSecurityGroup

  # Target Group for HTTP protocol
  AtlantisServerTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      VpcId: !Ref DefaultVPCId
      Port: 4141
      Protocol: HTTP
      TargetType: ip

  # Listener for HTTP Protocol
  AtlantisServerListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AtlantisServerTargetGroup
      LoadBalancerArn: !Ref AtlantisServerLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  LoadBalancerDNSName:
    Description: "The DNSName of the internal load balancer"
    Value: !GetAtt AtlantisServerLoadBalancer.DNSName
  LoadBalancerTargetGroupArn:
    Description: "The Arn of the internal load balancer target group"
    Value: !GetAtt AtlantisServerTargetGroup.TargetGroupArn